# Do not commit this file to your repository.
[development]
dynaconf_merge = true

[development.security]
# openssl rand -hex 32
SECRET_KEY = "42e09412d659ed07e23abb4fe2965b4d96a3987323f463c2b48dedd0c79d59f8"